# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 076a7aa724040c75cb3f0189f740cf463a970d0e75e382fe8165563f7ee3c928e996973c8163afdc65c0ced057ba21c4431610dba8bdfa9f1f5c9b592b809023

test:
  secret_key_base: 40d5c340cb819ef61e5612b4ad0c0959b65f81291a6e0d247cba8e21bcaa90ef09971fa3de876a2618b0cd19cb39e2f46872eb8f50eccf35e0be5787bc4a0809

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
